language: scala
scala:
  - 2.10.1
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - postgresql
  - mysql
before_script:
  - mysql -u root -e 'create database mysql_async_tests;'
  - psql -c 'create database netty_driver_test;' -U postgres
notifications:
  email:
    - linhares.mauricio@gmail.com